server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

  # ADDING CONFIGURATIONS THROUGH CONFIG-SERVER
  config:
      import: "optional:configserver:http://localhost:8085"

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE # 8081
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE # 8082
          predicates:
            - Path=/hotel/**, /employee/**
            #- Path=/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE # 8083
          predicates:
            - Path=/rating/**

#EUREKA CLIENT CONFIG : COMMENTED BECAUSE IMPORTED THROUGH CONFIG-SERVER
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
