server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#EUREKA CLIENT CONFIG
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1 #

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#  spring.datasource.url=jdbc:mysql://localhost:3306/spring_security_1?useSSL=false
#  spring.datasource.username=root
#  spring.datasource.password=0000
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=true
#server.port=8081